// Generated by gencpp from file motorcontrol/SrvInt32.msg
// DO NOT EDIT!


#ifndef MOTORCONTROL_MESSAGE_SRVINT32_H
#define MOTORCONTROL_MESSAGE_SRVINT32_H

#include <ros/service_traits.h>


#include <motorcontrol/SrvInt32Request.h>
#include <motorcontrol/SrvInt32Response.h>


namespace motorcontrol
{

struct SrvInt32
{

typedef SrvInt32Request Request;
typedef SrvInt32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvInt32
} // namespace motorcontrol


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motorcontrol::SrvInt32 > {
  static const char* value()
  {
    return "6cd15d79626e4186c53fc1d4dab3625b";
  }

  static const char* value(const ::motorcontrol::SrvInt32&) { return value(); }
};

template<>
struct DataType< ::motorcontrol::SrvInt32 > {
  static const char* value()
  {
    return "motorcontrol/SrvInt32";
  }

  static const char* value(const ::motorcontrol::SrvInt32&) { return value(); }
};


// service_traits::MD5Sum< ::motorcontrol::SrvInt32Request> should match 
// service_traits::MD5Sum< ::motorcontrol::SrvInt32 > 
template<>
struct MD5Sum< ::motorcontrol::SrvInt32Request>
{
  static const char* value()
  {
    return MD5Sum< ::motorcontrol::SrvInt32 >::value();
  }
  static const char* value(const ::motorcontrol::SrvInt32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::motorcontrol::SrvInt32Request> should match 
// service_traits::DataType< ::motorcontrol::SrvInt32 > 
template<>
struct DataType< ::motorcontrol::SrvInt32Request>
{
  static const char* value()
  {
    return DataType< ::motorcontrol::SrvInt32 >::value();
  }
  static const char* value(const ::motorcontrol::SrvInt32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motorcontrol::SrvInt32Response> should match 
// service_traits::MD5Sum< ::motorcontrol::SrvInt32 > 
template<>
struct MD5Sum< ::motorcontrol::SrvInt32Response>
{
  static const char* value()
  {
    return MD5Sum< ::motorcontrol::SrvInt32 >::value();
  }
  static const char* value(const ::motorcontrol::SrvInt32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::motorcontrol::SrvInt32Response> should match 
// service_traits::DataType< ::motorcontrol::SrvInt32 > 
template<>
struct DataType< ::motorcontrol::SrvInt32Response>
{
  static const char* value()
  {
    return DataType< ::motorcontrol::SrvInt32 >::value();
  }
  static const char* value(const ::motorcontrol::SrvInt32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTORCONTROL_MESSAGE_SRVINT32_H
